### ISSUE TITLE
Shortcode: Showing only jobs from one category not working

### ISSUE THREAD

**Issue by philippstakenborg** [threadi/wp-personio-integration-light#128]
The following shortcode should only show jobs from the recruitingCategory with the id 68.
However: Its still showing all the jobs from different categories. 

[personioPositions lang="de" showfilter="1" filter="recruitingCategory,schedule" filtertype="linklist"  templates="title,excerpt" excerpt="recruitingCategory,schedule" sort="asc" sortby="title" recruitingCategory="68"]

Do you know why that is? Is there an error in my shortcode? 

Also tried the short version of it, which also does not work:
[personioPositions recruitingCategory="68"]

**Comment by threadi** [comment]
Thanks for the hint. This is fixed in #130 and could be used with the next release.
