### ISSUE TITLE
Possibility to customise the detail view template

### ISSUE THREAD

**Issue by rogerg93** [threadi/wp-personio-integration-light#237]
Hello,

Thank you for creating and maintaining this product. We are using it on our Wordpress website. There is only one issue that we found. The detail page for each job position is auto generated by the plugin when the job is imported. Is there a way to customise the layout of the template?

**Comment by threadi** [comment]
Yes, this can already be done by customising the templates which is described here: https://github.com/threadi/wp-personio-integration-light/blob/master/doc/templates.md

If you are using a page builder (such as the Block Editor), you can also customise this page there. Many other page builders are also supported in the paid Pro version (Elementor, Avada, etc.). See: https://laolaweb.com/en/plugins/personio-wordpress-plugin/
